### ISSUE TITLE
Feature Request: Custom Role unique value

### ISSUE THREAD

**Issue by cuanl-cd** [Cloud-Direct-Monitoring/cd-monitoring-bootstrap#15]
Currently when deploying this Terraform module it creates a custom role called "Deployment Stacks Contributor" which is assignable at the Resource Group which is created. 

This works fine but presents an issue if needing to deploy the role again within the same tenant indicating that the current custom role already exists within the tenant. 

This can be manually modified within the module at deploy time but perhaps a unique value can be appended to the name to prevent the error? 

E.g Append the name of the Resource Group to the end of the `azurerm_role_definition` name : 

```
resource "azurerm_role_definition" "deployment_stacks_contributor" {
  name        = "Deployment Stacks Contributor - ${local.resource_group_name}"
  scope       = azurerm_resource_group.rg.id
  description = "Custom role to manage deployment stacks and deployments."

  permissions {
    actions = [
      "Microsoft.Resources/deploymentStacks/*",
      "Microsoft.Resources/deployments/*"
    ]
    not_actions = []
  }

  assignable_scopes = [
    azurerm_resource_group.rg.id
  ]
}
```

**Comment by richeney** [comment]
Once Deployment Stacks Contributor is released as an official in-built role then I assume that we can close this feature request.

**Comment by richeney** [comment]
@cuanl-cd We should bootstrap with this role and see how Contributor gets on.

**Comment by richeney** [comment]
For reference, here is the full set of actions in that provider type:

```shell
az provider operation show --namespace Microsoft.Resources --query "resourceTypes[?name == 'deploymentStacks'].operations[].name"
```
```json
[
  "Microsoft.Resources/deploymentStacks/read",
  "Microsoft.Resources/deploymentStacks/write",
  "Microsoft.Resources/deploymentStacks/delete",
  "Microsoft.Resources/deploymentStacks/manageDenySetting/action"
]
```
